quarkus.datasource.devservices.enabled=false

quarkus.flyway.locations=classpath:db/migration

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

servicetrack.jwt.expiracao-horas=8
servicetrack.jwt.decisao-orcamento.expiracao-horas=72
servicetrack.api.base-url=${SERVICETRACK_API_BASE_URL:http://localhost:8080}
mp.jwt.verify.issuer=service-track-api
mp.jwt.verify.publickey.location=classpath:keys/publicKey.pem
mp.jwt.verify.publickey.algorithm=RS256
smallrye.jwt.sign.key.location=classpath:keys/privateKey.pem

quarkus.rest-client.fipe-api.url=https://fipe.parallelum.com.br/api/v2
quarkus.rest-client.fipe-api.connect-timeout=5000
quarkus.rest-client.fipe-api.read-timeout=10000

quarkus.rest-client.unsplash-api.url=https://api.unsplash.com
quarkus.rest-client.unsplash-api.connect-timeout=5000
quarkus.rest-client.unsplash-api.read-timeout=10000
unsplash.chave-acesso=${UNSPLASH_CHAVE_ACESSO:}

quarkus.cache.caffeine.fipe-marcas-carros.expire-after-write=3600S
quarkus.cache.caffeine.fipe-modelos-carros.expire-after-write=3600S
quarkus.cache.caffeine.fipe-anos-carros.expire-after-write=3600S
quarkus.cache.caffeine.unsplash-imagens-veiculo.expire-after-write=1800S

quarkus.mailer.from=${QUARKUS_MAILER_FROM:no-reply@servicetrack.local}
quarkus.mailer.host=${QUARKUS_MAILER_HOST:localhost}

quarkus.qute.strict-rendering=false

