%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:servicetrack;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%dev.quarkus.h2.console.enabled=true
%dev.quarkus.h2.console.path=/h2-console

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:servicetrack}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:servicetrack}
%prod.quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/servicetrack}

quarkus.datasource.devservices.enabled=false
quarkus.hibernate-orm.database.generation=update

servicetrack.jwt.expiracao-horas=8

mp.jwt.verify.issuer=service-track-api
mp.jwt.verify.publickey.location=classpath:keys/publicKey.pem
mp.jwt.verify.publickey.algorithm=RS256

smallrye.jwt.sign.key.location=classpath:keys/privateKey.pem