%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:servicetrack;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
%dev.quarkus.h2.console.enabled=true
%dev.quarkus.h2.console.path=/h2-console
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with


%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME:servicetrack}
%prod.quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD:servicetrack}
%prod.quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/servicetrack}

quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%prod.quarkus.hibernate-orm.database.generation=${QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION:drop-and-create}

servicetrack.jwt.expiracao-horas=8

mp.jwt.verify.issuer=service-track-api
mp.jwt.verify.publickey.location=classpath:keys/publicKey.pem
mp.jwt.verify.publickey.algorithm=RS256

smallrye.jwt.sign.key.location=classpath:keys/privateKey.pem

quarkus.rest-client.fipe-api.url=https://fipe.parallelum.com.br/api/v2
quarkus.rest-client.fipe-api.connect-timeout=5000
quarkus.rest-client.fipe-api.read-timeout=10000

quarkus.rest-client.unsplash-api.url=https://api.unsplash.com
quarkus.rest-client.unsplash-api.connect-timeout=5000
quarkus.rest-client.unsplash-api.read-timeout=10000
unsplash.chave-acesso=${UNSPLASH_CHAVE_ACESSO:}

quarkus.cache.caffeine.fipe-marcas-carros.expire-after-write=3600S
quarkus.cache.caffeine.fipe-modelos-carros.expire-after-write=3600S
quarkus.cache.caffeine.fipe-anos-carros.expire-after-write=3600S
quarkus.cache.caffeine.unsplash-imagens-veiculo.expire-after-write=1800S
