quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:h2:mem:servicetrack;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2-console

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.mailer.mock=${QUARKUS_MAILER_MOCK:false}
quarkus.mailer.host=${QUARKUS_MAILER_HOST:localhost}
quarkus.mailer.port=${QUARKUS_MAILER_PORT:1025}
quarkus.mailer.start-tls=DISABLED
quarkus.mailer.auth-methods=DISABLED
quarkus.mailer.from=${QUARKUS_MAILER_FROM:no-reply@servicetrack.local}
