apiVersion: v1
kind: ConfigMap
metadata:
  name: service-track-config
  namespace: service-track
data:
  QUARKUS_PROFILE: "prod"
  DB_JDBC_URL: "${RDS_JDBC_URL}"
  SERVICETRACK_API_BASE_URL: "${API_BASE_URL}"
  QUARKUS_MAILER_FROM: "no-reply@clausilva.com.br"
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: "file:/keys/publicKey.pem"
  SMALLRYE_JWT_SIGN_KEY_LOCATION: "file:/keys/privateKey.pem"
