apiVersion: v1
kind: Secret
metadata:
  name: service-track-secret
  namespace: service-track
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: servicetrack
  QUARKUS_DATASOURCE_PASSWORD: servicetrack
  UNSPLASH_CHAVE_ACESSO: "local-placeholder"
