apiVersion: v1
kind: Secret
metadata:
  name: service-track-secret
  namespace: service-track
type: Opaque
stringData:
  QUARKUS_DATASOURCE_USERNAME: "${RDS_USERNAME}"
  QUARKUS_DATASOURCE_PASSWORD: "${RDS_PASSWORD}"
  UNSPLASH_CHAVE_ACESSO: "local-placeholder"
