openapi: 3.0.3
info:
  title: ServiceTrack API
  version: 1.0.0
  description: API para gerenciamento do sistema de atendimento da oficina mecânica

paths:
  /clientes:
    $ref: './paths/clientes/clientes.yaml'
  /mecanicos:
    $ref: './paths/mecanicos/mecanicos.yaml'
  /autenticacao:
    $ref: './paths/autenticacao/login.yaml'
