openapi: 3.0.3
info:
  title: ServiceTrack API
  version: 1.0.0
  description: API para gerenciamento do sistema de atendimento da oficina mecânica

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /clientes:
    $ref: './openApi/clientes/clientes.yaml'
  /clientes/{id}:
    $ref: './openApi/clientes/cliente_id.yaml'
  /mecanicos:
    $ref: './openApi/mecanicos/mecanicos.yaml'
  /mecanicos/{id}:
    $ref: './openApi/mecanicos/mecanico_id.yaml'
  /autenticacao:
    $ref: './openApi/autenticacao/login.yaml'
  /veiculos:
    $ref: './openApi/veiculo/veiculo.yaml'
  /veiculos/{id}:
    $ref: './openApi/veiculo/veiculo_id.yaml'
  /servicos:
    $ref: './openApi/servicos/servicos.yaml'
  /servicos/{id}:
    $ref: './openApi/servicos/servico_id.yaml'
  /insumos:
    $ref: './openApi/insumos/insumos.yaml'
  /insumos/{id}:
    $ref: './openApi/insumos/insumo_id.yaml'
  /catalogo/servicos:
    $ref: './openApi/catalogo/catalogo_servicos.yaml'
  /catalogo/insumos:
    $ref: './openApi/catalogo/catalogo_insumos.yaml'
  /ordem-servico:
    $ref: './openApi/ordemServico/ordemServico.yaml'
