package br.com.servicetrack.application.observabilidade.enums

import br.com.servicetrack.domain.auditoria.enums.TipoEntidade

enum class CodigoUseCase(
    val descricao: String,
    val entidade: TipoEntidade,
) {
    CLIENTE_CRIAR("Cadastro de cliente", TipoEntidade.USUARIO),
    CLIENTE_BUSCAR("Consulta de cliente", TipoEntidade.USUARIO),
    CLIENTE_ATUALIZAR("Atualizacao de cliente", TipoEntidade.USUARIO),
    CLIENTE_DESATIVAR("Desativacao de cliente", TipoEntidade.USUARIO),
    CLIENTE_RESETAR_SENHA("Alteracao de senha", TipoEntidade.USUARIO),
    MECANICO_CADASTRAR("Cadastro de mecanico", TipoEntidade.MECANICO),
    MECANICO_BUSCAR("Consulta de mecanico", TipoEntidade.MECANICO),
    MECANICO_LISTAR("Listagem de mecanicos", TipoEntidade.MECANICO),
    MECANICO_ATUALIZAR("Atualizacao de mecanico", TipoEntidade.MECANICO),
    VEICULO_CADASTRAR("Cadastro de veiculo", TipoEntidade.VEICULO),
    VEICULO_BUSCAR("Consulta de veiculo", TipoEntidade.VEICULO),
    VEICULO_LISTAR("Listagem de veiculos", TipoEntidade.VEICULO),
    VEICULO_ATUALIZAR("Atualizacao de veiculo", TipoEntidade.VEICULO),
    VEICULO_REMOVER("Remocao de veiculo", TipoEntidade.VEICULO),
    VEICULO_SUGESTOES_IMAGENS("Sugestao de imagens do veiculo", TipoEntidade.VEICULO),
    SERVICO_CRIAR("Cadastro de servico", TipoEntidade.SERVICO),
    SERVICO_BUSCAR("Consulta de servico", TipoEntidade.SERVICO),
    SERVICO_LISTAR("Listagem de servicos", TipoEntidade.SERVICO),
    SERVICO_ATUALIZAR("Atualizacao de servico", TipoEntidade.SERVICO),
    SERVICO_REMOVER("Remocao de servico", TipoEntidade.SERVICO),
    SERVICO_TEMPO_MEDIO("Consulta de tempo medio de conclusao", TipoEntidade.SERVICO),
    SERVICO_CATALOGO("Catalogo de servicos", TipoEntidade.SERVICO),
    INSUMO_CRIAR("Cadastro de insumo", TipoEntidade.INSUMO),
    INSUMO_BUSCAR("Consulta de insumo", TipoEntidade.INSUMO),
    INSUMO_LISTAR("Listagem de insumos", TipoEntidade.INSUMO),
    INSUMO_ATUALIZAR("Atualizacao de insumo", TipoEntidade.INSUMO),
    INSUMO_REMOVER("Remocao de insumo", TipoEntidade.INSUMO),
    INSUMO_CATALOGO("Catalogo de insumos", TipoEntidade.INSUMO),
    OS_CRIAR("Abertura de ordem de servico", TipoEntidade.ORDEM_SERVICO),
    OS_CRIAR_COMPLETA("Abertura completa de ordem de servico", TipoEntidade.ORDEM_SERVICO),
    OS_BUSCAR("Consulta de ordem de servico", TipoEntidade.ORDEM_SERVICO),
    OS_LISTAR("Listagem de ordens de servico", TipoEntidade.ORDEM_SERVICO),
    OS_ENVIAR_DIAGNOSTICO("Envio para diagnostico", TipoEntidade.ORDEM_SERVICO),
    OS_ASSOCIAR_ITENS("Associacao de itens ao diagnostico", TipoEntidade.ORDEM_SERVICO),
    OS_CONCLUIR_ITEM("Conclusao de item de servico", TipoEntidade.ORDEM_SERVICO),
    OS_CANCELAR("Cancelamento de ordem de servico", TipoEntidade.ORDEM_SERVICO),
    OS_FINALIZAR("Finalizacao de ordem de servico", TipoEntidade.ORDEM_SERVICO),
    OS_ENTREGAR("Entrega do veiculo", TipoEntidade.ORDEM_SERVICO),
    ORCAMENTO_GERAR("Geracao de orcamento", TipoEntidade.ORCAMENTO),
    ORCAMENTO_APROVAR("Aprovacao de orcamento", TipoEntidade.ORCAMENTO),
    ORCAMENTO_REPROVAR("Reprovacao de orcamento", TipoEntidade.ORCAMENTO),
    ORCAMENTO_APROVAR_EMAIL("Aprovacao de orcamento por magic link", TipoEntidade.ORCAMENTO),
    ORCAMENTO_REPROVAR_EMAIL("Reprovacao de orcamento por magic link", TipoEntidade.ORCAMENTO),
    NOTIFICACAO_ENFILEIRAR("Enfileiramento de notificacao", TipoEntidade.NOTIFICACAO),
    NOTIFICACAO_PROCESSAR_PENDENTES("Processamento de notificacoes pendentes", TipoEntidade.NOTIFICACAO),
    NOTIFICACAO_BUSCAR("Consulta de notificacao", TipoEntidade.NOTIFICACAO),
    NOTIFICACAO_LISTAR("Listagem de notificacoes", TipoEntidade.NOTIFICACAO),
    NOTIFICACAO_CONTAR_NAO_LIDAS("Contagem de notificacoes nao lidas", TipoEntidade.NOTIFICACAO),
    NOTIFICACAO_MARCAR_VISUALIZADA("Marcacao de notificacao como visualizada", TipoEntidade.NOTIFICACAO),
    DASHBOARD_RESUMO_CLIENTE("Resumo do dashboard do cliente", TipoEntidade.ORDEM_SERVICO),
}
